name: advent_of_code_2023
description: Project for Advent of Code 2023 submissions.
version: 1.0.0
repository: https://github.com/rajabilal555/advent_of_code_2023

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
